// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: api/usercenter/v1/login.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BecomeGameCoachRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameName     string `protobuf:"bytes,1,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	Level        string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	LevelPicture []byte `protobuf:"bytes,3,opt,name=level_picture,json=levelPicture,proto3" json:"level_picture,omitempty"`
}

func (x *BecomeGameCoachRequest) Reset() {
	*x = BecomeGameCoachRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usercenter_v1_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BecomeGameCoachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BecomeGameCoachRequest) ProtoMessage() {}

func (x *BecomeGameCoachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_usercenter_v1_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BecomeGameCoachRequest.ProtoReflect.Descriptor instead.
func (*BecomeGameCoachRequest) Descriptor() ([]byte, []int) {
	return file_api_usercenter_v1_login_proto_rawDescGZIP(), []int{0}
}

func (x *BecomeGameCoachRequest) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *BecomeGameCoachRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *BecomeGameCoachRequest) GetLevelPicture() []byte {
	if x != nil {
		return x.LevelPicture
	}
	return nil
}

type BecomeGameCoachReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BecomeGameCoachReply) Reset() {
	*x = BecomeGameCoachReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usercenter_v1_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BecomeGameCoachReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BecomeGameCoachReply) ProtoMessage() {}

func (x *BecomeGameCoachReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_usercenter_v1_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BecomeGameCoachReply.ProtoReflect.Descriptor instead.
func (*BecomeGameCoachReply) Descriptor() ([]byte, []int) {
	return file_api_usercenter_v1_login_proto_rawDescGZIP(), []int{1}
}

type RealNameVerificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealName      string `protobuf:"bytes,1,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`                  // 真名
	IdCardNumber  string `protobuf:"bytes,2,opt,name=id_card_number,json=idCardNumber,proto3" json:"id_card_number,omitempty"`    // 身份证号码
	IdCardFront   []byte `protobuf:"bytes,3,opt,name=id_card_front,json=idCardFront,proto3" json:"id_card_front,omitempty"`       // 身份证正面
	IdCardReverse []byte `protobuf:"bytes,4,opt,name=id_card_reverse,json=idCardReverse,proto3" json:"id_card_reverse,omitempty"` // 身份证反面
	Picture       []byte `protobuf:"bytes,5,opt,name=picture,proto3" json:"picture,omitempty"`                                    // 本人照片
}

func (x *RealNameVerificationRequest) Reset() {
	*x = RealNameVerificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usercenter_v1_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealNameVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameVerificationRequest) ProtoMessage() {}

func (x *RealNameVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_usercenter_v1_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameVerificationRequest.ProtoReflect.Descriptor instead.
func (*RealNameVerificationRequest) Descriptor() ([]byte, []int) {
	return file_api_usercenter_v1_login_proto_rawDescGZIP(), []int{2}
}

func (x *RealNameVerificationRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *RealNameVerificationRequest) GetIdCardNumber() string {
	if x != nil {
		return x.IdCardNumber
	}
	return ""
}

func (x *RealNameVerificationRequest) GetIdCardFront() []byte {
	if x != nil {
		return x.IdCardFront
	}
	return nil
}

func (x *RealNameVerificationRequest) GetIdCardReverse() []byte {
	if x != nil {
		return x.IdCardReverse
	}
	return nil
}

func (x *RealNameVerificationRequest) GetPicture() []byte {
	if x != nil {
		return x.Picture
	}
	return nil
}

type RealNameVerificationReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RealNameVerificationReply) Reset() {
	*x = RealNameVerificationReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usercenter_v1_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealNameVerificationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameVerificationReply) ProtoMessage() {}

func (x *RealNameVerificationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_usercenter_v1_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameVerificationReply.ProtoReflect.Descriptor instead.
func (*RealNameVerificationReply) Descriptor() ([]byte, []int) {
	return file_api_usercenter_v1_login_proto_rawDescGZIP(), []int{3}
}

type OrdinaryLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *OrdinaryLoginRequest) Reset() {
	*x = OrdinaryLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usercenter_v1_login_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrdinaryLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdinaryLoginRequest) ProtoMessage() {}

func (x *OrdinaryLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_usercenter_v1_login_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdinaryLoginRequest.ProtoReflect.Descriptor instead.
func (*OrdinaryLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_usercenter_v1_login_proto_rawDescGZIP(), []int{4}
}

func (x *OrdinaryLoginRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *OrdinaryLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type OrdinaryLoginReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *OrdinaryLoginReply) Reset() {
	*x = OrdinaryLoginReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usercenter_v1_login_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrdinaryLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdinaryLoginReply) ProtoMessage() {}

func (x *OrdinaryLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_usercenter_v1_login_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdinaryLoginReply.ProtoReflect.Descriptor instead.
func (*OrdinaryLoginReply) Descriptor() ([]byte, []int) {
	return file_api_usercenter_v1_login_proto_rawDescGZIP(), []int{5}
}

func (x *OrdinaryLoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AdminLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AdminLoginRequest) Reset() {
	*x = AdminLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usercenter_v1_login_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginRequest) ProtoMessage() {}

func (x *AdminLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_usercenter_v1_login_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginRequest.ProtoReflect.Descriptor instead.
func (*AdminLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_usercenter_v1_login_proto_rawDescGZIP(), []int{6}
}

func (x *AdminLoginRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AdminLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminLoginReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AdminLoginReply) Reset() {
	*x = AdminLoginReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usercenter_v1_login_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginReply) ProtoMessage() {}

func (x *AdminLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_usercenter_v1_login_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginReply.ProtoReflect.Descriptor instead.
func (*AdminLoginReply) Descriptor() ([]byte, []int) {
	return file_api_usercenter_v1_login_proto_rawDescGZIP(), []int{7}
}

func (x *AdminLoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type OrdinaryRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Code     string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *OrdinaryRegisterRequest) Reset() {
	*x = OrdinaryRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usercenter_v1_login_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrdinaryRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdinaryRegisterRequest) ProtoMessage() {}

func (x *OrdinaryRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_usercenter_v1_login_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdinaryRegisterRequest.ProtoReflect.Descriptor instead.
func (*OrdinaryRegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_usercenter_v1_login_proto_rawDescGZIP(), []int{8}
}

func (x *OrdinaryRegisterRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *OrdinaryRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *OrdinaryRegisterRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type OrdinaryRegisterReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrdinaryRegisterReply) Reset() {
	*x = OrdinaryRegisterReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_usercenter_v1_login_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrdinaryRegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdinaryRegisterReply) ProtoMessage() {}

func (x *OrdinaryRegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_usercenter_v1_login_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdinaryRegisterReply.ProtoReflect.Descriptor instead.
func (*OrdinaryRegisterReply) Descriptor() ([]byte, []int) {
	return file_api_usercenter_v1_login_proto_rawDescGZIP(), []int{9}
}

var File_api_usercenter_v1_login_proto protoreflect.FileDescriptor

var file_api_usercenter_v1_login_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x70, 0x0a, 0x16, 0x42, 0x65, 0x63, 0x6f, 0x6d, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43,
	0x6f, 0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x23,
	0x0a, 0x0d, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x50, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x42, 0x65, 0x63, 0x6f, 0x6d, 0x65, 0x47, 0x61, 0x6d,
	0x65, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0xc6, 0x01, 0x0a, 0x1b,
	0x52, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72,
	0x65, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x64, 0x5f, 0x63,
	0x61, 0x72, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22,
	0x0a, 0x0d, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x46, 0x72, 0x6f,
	0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x72, 0x65,
	0x76, 0x65, 0x72, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x69, 0x64, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x69,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x4f, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x2a, 0x0a, 0x12, 0x4f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4c,
	0x0a, 0x11, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x27, 0x0a, 0x0f,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x66, 0x0a, 0x17, 0x4f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x17, 0x0a,
	0x15, 0x4f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xc7, 0x01, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x64, 0x0a, 0x0d, 0x4f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x76, 0x31,
	0x2e, 0x4f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x12, 0x19, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x58, 0x0a, 0x0a, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x43,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x32, 0x85, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x79, 0x0a,
	0x10, 0x4f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2d, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x27, 0x22, 0x1c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x3a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x8a, 0x02, 0x0a, 0x05, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x12, 0x89, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x31, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x2b, 0x22, 0x20, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x2f, 0x52, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x75,
	0x0a, 0x0f, 0x42, 0x65, 0x63, 0x6f, 0x6d, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x61, 0x63,
	0x68, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x63, 0x6f, 0x6d, 0x65, 0x47, 0x61, 0x6d,
	0x65, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x65, 0x63, 0x6f, 0x6d, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x61,
	0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x26, 0x22,
	0x1b, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x42, 0x65, 0x63,
	0x6f, 0x6d, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x61, 0x63, 0x68, 0x3a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x31, 0x0a, 0x11, 0x64, 0x65, 0x76, 0x2e, 0x6b, 0x72, 0x61,
	0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x42, 0x02, 0x56, 0x31, 0x50, 0x01,
	0x5a, 0x16, 0x61, 0x74, 0x74, 0x61, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_usercenter_v1_login_proto_rawDescOnce sync.Once
	file_api_usercenter_v1_login_proto_rawDescData = file_api_usercenter_v1_login_proto_rawDesc
)

func file_api_usercenter_v1_login_proto_rawDescGZIP() []byte {
	file_api_usercenter_v1_login_proto_rawDescOnce.Do(func() {
		file_api_usercenter_v1_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_usercenter_v1_login_proto_rawDescData)
	})
	return file_api_usercenter_v1_login_proto_rawDescData
}

var file_api_usercenter_v1_login_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_usercenter_v1_login_proto_goTypes = []interface{}{
	(*BecomeGameCoachRequest)(nil),      // 0: v1.BecomeGameCoachRequest
	(*BecomeGameCoachReply)(nil),        // 1: v1.BecomeGameCoachReply
	(*RealNameVerificationRequest)(nil), // 2: v1.RealNameVerificationRequest
	(*RealNameVerificationReply)(nil),   // 3: v1.RealNameVerificationReply
	(*OrdinaryLoginRequest)(nil),        // 4: v1.OrdinaryLoginRequest
	(*OrdinaryLoginReply)(nil),          // 5: v1.OrdinaryLoginReply
	(*AdminLoginRequest)(nil),           // 6: v1.AdminLoginRequest
	(*AdminLoginReply)(nil),             // 7: v1.AdminLoginReply
	(*OrdinaryRegisterRequest)(nil),     // 8: v1.OrdinaryRegisterRequest
	(*OrdinaryRegisterReply)(nil),       // 9: v1.OrdinaryRegisterReply
}
var file_api_usercenter_v1_login_proto_depIdxs = []int32{
	4, // 0: v1.Login.OrdinaryLogin:input_type -> v1.OrdinaryLoginRequest
	6, // 1: v1.Login.AdminLogin:input_type -> v1.AdminLoginRequest
	8, // 2: v1.Register.OrdinaryRegister:input_type -> v1.OrdinaryRegisterRequest
	2, // 3: v1.Apply.RealNameVerification:input_type -> v1.RealNameVerificationRequest
	0, // 4: v1.Apply.BecomeGameCoach:input_type -> v1.BecomeGameCoachRequest
	5, // 5: v1.Login.OrdinaryLogin:output_type -> v1.OrdinaryLoginReply
	7, // 6: v1.Login.AdminLogin:output_type -> v1.AdminLoginReply
	9, // 7: v1.Register.OrdinaryRegister:output_type -> v1.OrdinaryRegisterReply
	3, // 8: v1.Apply.RealNameVerification:output_type -> v1.RealNameVerificationReply
	1, // 9: v1.Apply.BecomeGameCoach:output_type -> v1.BecomeGameCoachReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_usercenter_v1_login_proto_init() }
func file_api_usercenter_v1_login_proto_init() {
	if File_api_usercenter_v1_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_usercenter_v1_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BecomeGameCoachRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usercenter_v1_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BecomeGameCoachReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usercenter_v1_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealNameVerificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usercenter_v1_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealNameVerificationReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usercenter_v1_login_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrdinaryLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usercenter_v1_login_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrdinaryLoginReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usercenter_v1_login_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usercenter_v1_login_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminLoginReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usercenter_v1_login_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrdinaryRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_usercenter_v1_login_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrdinaryRegisterReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_usercenter_v1_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_usercenter_v1_login_proto_goTypes,
		DependencyIndexes: file_api_usercenter_v1_login_proto_depIdxs,
		MessageInfos:      file_api_usercenter_v1_login_proto_msgTypes,
	}.Build()
	File_api_usercenter_v1_login_proto = out.File
	file_api_usercenter_v1_login_proto_rawDesc = nil
	file_api_usercenter_v1_login_proto_goTypes = nil
	file_api_usercenter_v1_login_proto_depIdxs = nil
}
